ng generate component AL-component
ng generate component AK-component
ng generate component AZ-component
ng generate component AR-component
ng generate component CA-component
ng generate component CO-component
ng generate component CT-component
ng generate component DC-component
ng generate component DE-component
ng generate component FL-component
ng generate component GA-component
ng generate component HI-component
ng generate component ID-component
ng generate component IL-component
ng generate component IN-component
ng generate component IA-component
ng generate component KS-component
ng generate component KY-component
ng generate component LA-component
ng generate component ME-component
ng generate component MD-component
ng generate component MA-component
ng generate component MI-component
ng generate component MN-component
ng generate component MS-component
ng generate component MO-component
ng generate component MT-component
ng generate component NE-component
ng generate component NV-component
ng generate component NH-component
ng generate component NJ-component
ng generate component NM-component
ng generate component NY-component
ng generate component NC-component
ng generate component ND-component
ng generate component OH-component
ng generate component OK-component
ng generate component OR-component
ng generate component PA-component
ng generate component RI-component
ng generate component SC-component
ng generate component SD-component
ng generate component TN-component
ng generate component TX-component
ng generate component UT-component
ng generate component VT-component
ng generate component VA-component
ng generate component WA-component
ng generate component WV-component
ng generate component WI-component
ng generate component WY-component
