ng generate component AL
ng generate component AK
ng generate component AZ
ng generate component AR
ng generate component CA
ng generate component CO
ng generate component CT
ng generate component DC
ng generate component DE
ng generate component FL
ng generate component GA
ng generate component HI
ng generate component ID
ng generate component IL
ng generate component IN
ng generate component IA
ng generate component KS
ng generate component KY
ng generate component LA
ng generate component ME
ng generate component MD
ng generate component MA
ng generate component MI
ng generate component MN
ng generate component MS
ng generate component MO
ng generate component MT
ng generate component NE
ng generate component NV
ng generate component NH
ng generate component NJ
ng generate component NM
ng generate component NY
ng generate component NC
ng generate component ND
ng generate component OH
ng generate component OK
ng generate component OR
ng generate component PA
ng generate component RI
ng generate component SC
ng generate component SD
ng generate component TN
ng generate component TX
ng generate component UT
ng generate component VT
ng generate component VA
ng generate component WA
ng generate component WV
ng generate component WI
ng generate component WY
